<?php
return array(
	array(
		'name'=>'概览',
		'css'=>'ic-home',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'开始',
							'css'=>'ic-cmd',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'仪表盘',
							'css'=>'ic-meter',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						
					),
		'children'=>''
	),
	array(
		'name'=>'P2P借贷',
		'css'=>'ic-coin',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'融资申请',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
		'children'=>''
	),
	array(
		'name'=>'孔方宝',
		'css'=>'ic-IcoMoon',
		'link'=>'',
		'submenu'=>'',
		'children'=>array(
						array(
							'name'=>'概览',
							'css'=>'ic-cmd',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'收益率设置',
							'css'=>'ic-cog',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'用户资金变更记录',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
	),
	array(
		'name'=>'众筹',
		'css'=>'ic-feed',
		'link'=>'',
		'submenu'=>'',
		'children'=>''
	),
	array(
		'name'=>'积分商城',
		'css'=>'ic-cart',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'产品',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'分类',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'兑换订单',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
		'children'=>''
	),
	array(
		'name'=>'营销活动',
		'css'=>'ic-gift',
		'link'=>'',
		'submenu'=>'',
		'children'=>''
	),
	array(
		'name'=>'客服中心',
		'css'=>'ic-users',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'充值',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
						array(
							'name'=>'提现',
							'css'=>'',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
		'children'=>''
	),
	array(
		'name'=>'统计 · 报表',
		'css'=>'ic-bars',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'孔方宝收益记录',
							'css'=>'ic-IcoMoon',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
		'children'=>''
	),
	array(
		'name'=>'系统设置',
		'css'=>'ic-cog',
		'link'=>'',
		'submenu'=>array(
						array(
							'name'=>'权限设置',
							'css'=>'ic-equalizer',
							'link'=>'',
							'submenu'=>'',
							'children'=>''
						),
					),
		'children'=>''
	),
);